"""empty message

Revision ID: 736d8a1a81cc
Revises: 
Create Date: 2021-01-12 19:56:07.777275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736d8a1a81cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('gender', sa.Enum('M', 'F', name='gender_types'), nullable=True))
    op.drop_constraint('movie_actors_actor_id_fkey', 'movie_actors', type_='foreignkey')
    op.drop_constraint('movie_actors_movie_id_fkey', 'movie_actors', type_='foreignkey')
    op.create_foreign_key(None, 'movie_actors', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_actors', 'actor', ['actor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_actors', type_='foreignkey')
    op.drop_constraint(None, 'movie_actors', type_='foreignkey')
    op.create_foreign_key('movie_actors_movie_id_fkey', 'movie_actors', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key('movie_actors_actor_id_fkey', 'movie_actors', 'actor', ['actor_id'], ['id'])
    op.drop_column('actor', 'gender')
    # ### end Alembic commands ###
